services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - inspectai-app-network
  ui:
    build:
      context: .
      dockerfile: ui.Dockerfile
    ports:
      - "8501:8501"
    networks:
      - inspectai-app-network
    volumes:
      - "./src/ui/:/usr/local/app/ui/"
    environment:
      - API_URL=http://api:8000
networks:
  inspectai-app-network:
    driver: bridge
